/*
 * generated by Xtext
 */
package net.sf.psstools.lang.ui.contentassist

import net.sf.psstools.lang.ui.contentassist.AbstractPSSProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PSSProposalProvider extends AbstractPSSProposalProvider {
}
