/*
* generated by Xtext
*/
package net.sf.psstools.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PSSStandaloneSetup extends PSSStandaloneSetupGenerated{

	public static void doSetup() {
		new PSSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

