/*
 * generated by Xtext
 */
package net.sf.psstools.lang.ui.contentassist

import net.sf.psstools.lang.ui.contentassist.AbstractPSSProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class PSSProposalProvider extends AbstractPSSProposalProvider {
}
