/*
 * generated by Xtext
 */
package net.sf.psstools.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PSSUiModule extends net.sf.psstools.lang.ui.AbstractPSSUiModule {
	public PSSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
