/*
 * generated by Xtext
 */
package net.sf.psstools.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import net.sf.psstools.lang.ui.internal.PSSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PSSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PSSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PSSActivator.getInstance().getInjector(PSSActivator.NET_SF_PSSTOOLS_LANG_PSS);
	}
	
}
