/*
* generated by Xtext
*/
package net.sf.psstools.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PSSUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return net.sf.psstools.lang.ui.internal.PSSActivator.getInstance().getInjector("net.sf.psstools.lang.PSS");
	}
	
}
