/*
 * generated by Xtext
 */
package net.sf.psstools.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PSSRuntimeModule extends net.sf.psstools.lang.AbstractPSSRuntimeModule {

}
